export const GET_LISTS_REQUEST = 'GET_LISTS_REQUEST';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';

export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';

export const REMOVE_LIST_REQUEST = 'REMOVE_LIST_REQUEST';
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS';

export const RENAME_LIST_REQUEST = 'RENAME_LIST_REQUEST';
export const RENAME_LIST_SUCCESS = 'RENAME_LIST_SUCCESS';

export const FIND_MAX_LIST_ID = 'FIND_MAX_LIST_ID';
export const INCREASE_MAX_LIST_ID = 'INCREASE_MAX_LIST_ID';
