export default {
    GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
    GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',

    GET_TASKS_BY_LIST_ID_REQUEST: 'GET_TASKS_BY_LIST_ID_REQUEST',
    GET_TASKS_BY_LIST_ID_SUCCESS: 'GET_TASKS_BY_LIST_ID_SUCCESS',

    CHANGE_TASK_STATE_REQUEST: 'CHANGE_TASK_STATE_REQUEST',
    CHANGE_TASK_STATE_SUCCESS: 'CHANGE_TASK_STATE_SUCCESS',

    ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',

    REMOVE_TASK_REQUEST: 'REMOVE_TASK_REQUEST',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',

    MOVE_TASK_UP_REQUEST: 'MOVE_TASK_UP_REQUEST',
    MOVE_TASK_UP_SUCCESS: 'MOVE_TASK_UP_SUCCESS',

    MOVE_TASK_DOWN_REQUEST: 'MOVE_TASK_DOWN_REQUEST',
    MOVE_TASK_DOWN_SUCCESS: 'MOVE_TASK_DOWN_SUCCESS',

    SET_NEW_LIST:'SET_NEW_LIST'
}
